### ISSUE TITLE
Data quality issue: Missing Vaccination Data

### ISSUE THREAD

**Issue by mswanson-nmdp** [starschema/COVID-19-data#336] opened 2021-03-08 18:58 UTC
**Describe the bug**
 PUBLIC.JHU_VACCINES is missing from the COVID dataset - this data was available until recently - wondering if it was removed in error or if it is something that i can find elsewhere?

**Comment by tfoldi** [comment] 2021-03-08 19:04
It should be there, seems like a sharing issue. What is your snowflake region?

**Comment by mswanson-nmdp** [comment] 2021-03-08 19:05
i'm in us-east-1

**Comment by tfoldi** [comment] 2021-03-08 19:11
Yes, several tables were missing from that region. I re-added them manually, now it should work. 

We are in the process to switch to replicate not just the data, but the share itself between regions too. My guess that this is the root cause, but I will double check.

**Comment by mswanson-nmdp** [comment] 2021-03-08 19:12
thank you - we greatly appreciate the fast response on this! -- enjoy the day

**Comment by mswanson-nmdp** [comment] 2021-03-08 19:29
how long will this change take to appear on our share? i'm still not seeing the vaccine table in the lake we have set up

**Comment by tfoldi** [comment] 2021-03-09 15:40
It should be available immediately. If the issue still persist please send a note to support@starschema.com with your snowflake account id. thank you!

**Comment by chrisvoncsefalvay** [comment] 2021-04-28 18:22
Hi @mswanson-nmdp – has this resolved for you?

**Comment by chrisvoncsefalvay** [comment] 2021-05-07 20:57
Hi @mswanson-nmdp – I'm closing this down. If you still have issues, please feel free to request for the issue to be reopened. Thank you!

**Closed as completed** 2021-05-07 20:58 UTC
Labels: bug, Snowflake
